-- Sunstrade volatility metrics and user-configurable volatility alerts.
-- Run once in Supabase SQL Editor before deploying the app.

create table if not exists public.asset_volatility_metrics (
  symbol text primary key references public.assets(symbol) on update cascade on delete cascade,
  price numeric not null check (price >= 0),
  volatility_pct numeric not null check (volatility_pct >= 0),
  atr_14 numeric not null check (atr_14 >= 0),
  atr_pct numeric not null check (atr_pct >= 0),
  interval text not null default '1d',
  sample_size integer not null default 20 check (sample_size > 0),
  source text not null default 'binance',
  calculated_at timestamptz not null default now()
);

create table if not exists public.volatility_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null references public.assets(symbol) on update cascade on delete cascade,
  threshold_pct numeric not null check (threshold_pct > 0 and threshold_pct <= 1000),
  condition text not null check (condition in ('above', 'below')),
  is_active boolean not null default true,
  last_triggered_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.volatility_alert_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  alert_id bigint references public.volatility_alerts(id) on delete set null,
  symbol text not null,
  volatility_pct numeric not null,
  threshold_pct numeric not null,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists volatility_alerts_active_idx
  on public.volatility_alerts (is_active, symbol);
create index if not exists volatility_notifications_user_idx
  on public.volatility_alert_notifications (user_id, created_at desc);

alter table public.asset_volatility_metrics enable row level security;
alter table public.volatility_alerts enable row level security;
alter table public.volatility_alert_notifications enable row level security;

drop policy if exists "Volatility metrics readable by everyone" on public.asset_volatility_metrics;
create policy "Volatility metrics readable by everyone"
  on public.asset_volatility_metrics for select using (true);

drop policy if exists "Users manage own volatility alerts" on public.volatility_alerts;
create policy "Users manage own volatility alerts"
  on public.volatility_alerts for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users read own volatility notifications" on public.volatility_alert_notifications;
create policy "Users read own volatility notifications"
  on public.volatility_alert_notifications for select
  using (auth.uid() = user_id);

-- Only server-side service-role code should write calculated metrics and notifications.
