"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@supabase/supabase-js";
import "./portfolio.css";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type Position={symbol:string;qty:number;avg_price:number}; type Asset={symbol:string;name:string;price:number;prev_close:number|null}; type Order={symbol:string;side:string;status:string;qty:number;filled_price:number|null;created_at:string;filled_at:string|null};
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const icon=(s:string)=>({BTC:"₿",ETH:"◆",BNB:"◆",SOL:"≋",XRP:"✕",DOGE:"Ð",ADA:"●",LTC:"Ł",EUR:"€",USD:"$"} as Record<string,string>)[s.split("/")[0]]||s[0];
export default function PortfolioPage(){
 const [user,setUser]=useState<any>(null),[balance,setBalance]=useState(0),[positions,setPositions]=useState<Position[]>([]),[orders,setOrders]=useState<Order[]>([]),[assets,setAssets]=useState<Asset[]>([]),[loading,setLoading]=useState(true),[tab,setTab]=useState<"positions"|"orders"|"history">("positions");
 const load=async(id:string)=>{const [w,p,o,a]=await Promise.all([supabase.from("wallets").select("cash_balance").eq("user_id",id).maybeSingle(),supabase.from("positions").select("symbol,qty,avg_price").eq("user_id",id).order("symbol"),supabase.from("orders").select("symbol,side,status,qty,filled_price,created_at,filled_at").eq("user_id",id).order("created_at",{ascending:false}).limit(50),supabase.from("assets").select("symbol,name,price,prev_close").order("symbol")]);if(!w.error)setBalance(Number(w.data?.cash_balance||0));if(!p.error)setPositions((p.data||[]).map(x=>({symbol:x.symbol,qty:Number(x.qty),avg_price:Number(x.avg_price)})));if(!o.error)setOrders((o.data||[]) as Order[]);if(!a.error)setAssets((a.data||[]).map(x=>({symbol:x.symbol,name:x.name,price:Number(x.price),prev_close:x.prev_close==null?null:Number(x.prev_close)})))};
 useEffect(()=>{let alive=true;(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!alive)return;if(!session?.user){window.location.href="/login";return}setUser(session.user);await load(session.user.id);if(alive)setLoading(false)})();return()=>{alive=false}},[]);
 useEffect(()=>{if(!user)return;const id=user.id;const ch=supabase.channel("sunstrade-portfolio").on("postgres_changes",{event:"*",schema:"public",table:"wallets",filter:`user_id=eq.${id}`},()=>void load(id)).on("postgres_changes",{event:"*",schema:"public",table:"positions",filter:`user_id=eq.${id}`},()=>void load(id)).on("postgres_changes",{event:"*",schema:"public",table:"orders",filter:`user_id=eq.${id}`},()=>void load(id)).subscribe();return()=>{void supabase.removeChannel(ch)}},[user]);
 const rows=useMemo(()=>positions.map(p=>{const a=assets.find(x=>x.symbol===p.symbol),current=a?.price||p.avg_price,value=current*p.qty,pl=(current-p.avg_price)*p.qty;return {...p,name:a?.name||p.symbol,value,pl,plPct:p.avg_price?((current-p.avg_price)/p.avg_price)*100:0}}),[positions,assets]);
 const invested=rows.reduce((s,r)=>s+r.avg_price*r.qty,0),market=rows.reduce((s,r)=>s+r.value,0),equity=balance+market,openPL=market-invested;
 if(loading)return <main className="portfolio-loading"><div>S</div><p>Loading portfolio…</p></main>;
 return <main className="sun-portfolio-page">
  <header className="portfolio-header"><Link href="/dashboard" className="portfolio-back">‹</Link><div><span>ACCOUNT</span><h1>Portfolio</h1></div><Link href="/profile" className="portfolio-avatar">{(user?.user_metadata?.full_name||user?.email||"S")[0].toUpperCase()}</Link></header>
  <section className="portfolio-hero"><div className="portfolio-hero-top"><span>Total Equity</span><span>● Live</span></div><strong>{money(equity)}</strong><div className={openPL>=0?"positive":"negative"}>{openPL>=0?"+":""}{money(openPL)} <small>unrealized P/L</small></div></section>
  <section className="portfolio-stats"><div><span>Free Margin</span><b>{money(balance)}</b></div><div><span>Used Margin</span><b>{money(market)}</b></div><div><span>Today's P/L</span><b className={openPL>=0?"positive":"negative"}>{openPL>=0?"+":""}{money(openPL)}</b></div><div><span>Margin Level</span><b>{market>0?((equity/market)*100).toFixed(2)+"%":"—"}</b></div></section>
  <section className="portfolio-card"><div className="portfolio-card-head"><div><span>OPEN POSITIONS</span><h2>Your holdings</h2></div><Link href="/trade">Trade →</Link></div>{rows.length?<div>{rows.map(r=><Link href={"/trade?symbol="+encodeURIComponent(r.symbol)} className="portfolio-position" key={r.symbol}><i>{icon(r.symbol)}</i><span><b>{r.symbol}</b><small>{r.name} · {r.qty}</small></span><em><b>{money(r.value)}</b><small className={r.pl>=0?"positive":"negative"}>{r.pl>=0?"+":""}{money(r.pl)} · {r.plPct>=0?"+":""}{r.plPct.toFixed(2)}%</small></em></Link>)}</div>:<div className="portfolio-empty">No open positions yet. <Link href="/trade">Start trading →</Link></div>}</section>
  <section className="portfolio-card"><div className="portfolio-card-head"><div><span>ASSET ALLOCATION</span><h2>Where your equity is</h2></div></div><div className="allocation-row"><span><i className="dot crypto"/>Positions</span><b>{equity?((market/equity)*100).toFixed(1):"0"}%</b><div><i style={{width:`${equity?Math.min(100,market/equity*100):0}%`}}/></div></div><div className="allocation-row"><span><i className="dot cash"/>Cash</span><b>{equity?((balance/equity)*100).toFixed(1):"100"}%</b><div><i style={{width:`${equity?Math.min(100,balance/equity*100):100}%`}}/></div></div></section>
  <section className="portfolio-card"><div className="portfolio-tabs"><button className={tab==="positions"?"active":""} onClick={()=>setTab("positions")}>Positions <b>{positions.length}</b></button><button className={tab==="orders"?"active":""} onClick={()=>setTab("orders")}>Orders <b>{orders.length}</b></button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>History <b>{orders.filter(o=>o.status==="filled").length}</b></button></div>{tab==="positions"?<div className="portfolio-list-note">Live positions are calculated from your simulated account and current market reference prices.</div>:<div>{orders.filter(o=>tab==="orders"?o.status!=="filled":o.status==="filled").slice(0,12).map((o,i)=><div className="portfolio-order" key={i}><span><b>{o.side.toUpperCase()} {o.symbol}</b><small>{o.qty} units · {o.status}</small></span><em>{o.filled_price?money(Number(o.filled_price)*Number(o.qty)):"Pending"}<small>{new Date(o.filled_at||o.created_at).toLocaleDateString()}</small></em></div>)}</div>}</section>
  <nav className="portfolio-nav"><Link href="/dashboard"><span>⌂</span><b>Home</b></Link><Link href="/markets"><span>◉</span><b>Markets</b></Link><Link href="/trade"><span>↗</span><b>Trade</b></Link><Link className="active" href="/portfolio"><span>▤</span><b>Portfolio</b></Link><Link href="/more"><span>☰</span><b>More</b></Link></nav>
 </main>;
}